name: ✨ Feature Request
description: Suggest a new feature or enhancement for this project
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees:
  - KevinTCoughlin
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem-description
    attributes:
      label: 🧐 Problem Description
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: 💡 Proposed Solution
      description: A clear and concise description of what you want to happen.
      placeholder: Describe your ideal solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternatives Considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: What alternatives have you considered?
    validations:
      required: false

  - type: dropdown
    id: feature-type
    attributes:
      label: 🏷️ Feature Type
      description: What type of feature is this?
      options:
        - UI/UX Enhancement
        - Performance Improvement
        - New Functionality
        - Developer Experience
        - Documentation
        - Accessibility
        - Security
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: ⚡ Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my work
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Additional Context
      description: Add any other context, screenshots, or examples about the feature request here.
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: terms
    attributes:
      label: 📋 Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing feature requests before creating this one
          required: true
        - label: I have provided a clear description of the problem and proposed solution
          required: true